
FROM node:22.11.0

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first for dependency caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose Angular's default port (4200)
EXPOSE 4200

# Run the Angular development server
CMD ["npm", "run", "ng", "--", "serve", "--host", "0.0.0.0", "--poll", "2000"]

